sudo: required

services:
  - docker

script:
  - docker-compose build
  - docker-compose up -d
  - sleep 30
  - docker-compose exec app bin/console security:check
  - docker-compose exec app bin/console doctrine:schema:create
  - docker-compose exec app docker/varnish/test-varnish.sh